const express=require('express')
const {userLogin,userRegistration}=require('../Controllers/userCredentials.controller')
const { getProperties,addProperties, upload, addLikes ,getAddedProperties} = require('../Controllers/properties.controller')
const usrerIsLogin = require('../Middlewares/userIsLogin.middleware')
const userIsAdmin = require('../Middlewares/userIsAdmin.middleware')
const {sellerDetails} = require('../Controllers/sellerDetails.controller')
const route=express.Router()
route.post("/login",userLogin)
route.post("/reg",userRegistration)
route.get('/getproperties',getProperties)
route.post('/addproperty',usrerIsLogin,userIsAdmin,upload.single("image") ,addProperties)
route.get('/sellerdetails',usrerIsLogin,sellerDetails)
route.post('/like',addLikes)
route.get('/getaddedproperties',userIsAdmin,getAddedProperties)
module.exports=route